# _config.yml
title: 维护中！
description: 固定布局的罗马风格维基
baseurl: ""  # 如果部署到子目录，如 /blog，则填写 "/blog"
url: ""  # 你的 GitHub Pages 地址

# 主题设置（这里我们使用自定义主题）
theme: null
markdown: kramdown
highlighter: rouge

# 排除文件
exclude:
  - README.md
  - .gitignore
  - LICENSE

navigation:
  - title: 首页
    url: /
    icon: 🏠
  - title: 国家介绍
    url: /introduction/
    icon: 🏛️
  - title: 新闻报刊
    url: /news/home/
    icon: 📰
  - title: 罗马历史
    url: /history/
    icon: 📜
  - title: 罗马人物
    url: /people/home/
    icon: 🧑
  - title: 罗马音乐
    url: /music/
    icon: 🎵
  - title: 关于
    url: /about/
    icon: ℹ️
  - title: 隐藏页面
    url: /hidden/
    icon: 😃

navigation_news:
  - title: 新闻&报刊总览
    url: /news/home/
    icon: 📰
  - title: 罗马人民报
    url: /news/peoples-newspaper/
    icon: 🗞️
  - title: 罗马联合速报
    url: /news/united-express/
    icon: 🗞️

navigation_people:
  - title: 人物总览
    url: /people/home/
    icon: 🏛️
  - title: 尤利乌斯·凯撒
    url: /people/julius-caesar/
    icon: ⚔️
  - title: 奥古斯都
    url: /people/augustus/
    icon: 👑
  - title: 西塞罗
    url: /people/cicero/
    icon: 📜